const mongoose = require('mongoose');

const mediaSchema = new mongoose.Schema(
  {
    // ── Ownership ──────────────────────────────────────────────────────────────
    uploadedBy: {
      userId: { type: String, required: true },
      name: { type: String, required: true },
      email: { type: String, required: true },
    },

    // ── Classification ─────────────────────────────────────────────────────────
    /**
     * category: what this media is used for
     * - avatar       : user profile picture
     * - event_banner : main event cover image
     * - event_gallery: additional event images
     * - document     : PDFs, presentations etc (raw)
     * - video        : event recap / promo videos
     * - general      : any other upload
     */
    category: {
      type: String,
      enum: ['avatar', 'event_banner', 'event_gallery', 'document', 'video', 'general'],
      default: 'general',
    },

    // ── Entity link (optional) ─────────────────────────────────────────────────
    // e.g. link this media to a specific event or user
    entityType: {
      type: String,
      enum: ['event', 'user', null],
      default: null,
    },
    entityId: {
      type: String,
      default: null,
    },

    // ── File metadata ──────────────────────────────────────────────────────────
    originalName: {
      type: String,
      required: true,
    },
    mimeType: {
      type: String,
      required: true,
    },
    resourceType: {
      type: String,
      enum: ['image', 'video', 'raw'],
      required: true,
    },
    format: {
      type: String, // e.g. 'jpg', 'mp4', 'pdf'
    },
    sizeBytes: {
      type: Number, // original file size
    },

    // ── Cloudinary data ────────────────────────────────────────────────────────
    cloudinaryPublicId: {
      type: String,
      required: true,
      unique: true,
    },
    url: {
      type: String,
      required: true,
    },
    secureUrl: {
      type: String,
      required: true,
    },

    // ── Dimensions (images/videos) ─────────────────────────────────────────────
    width: { type: Number },
    height: { type: Number },
    duration: { type: Number }, // video duration in seconds

    // ── Thumbnails (auto-generated by Cloudinary for videos) ──────────────────
    thumbnailUrl: {
      type: String,
      default: '',
    },

    // ── Alt text / caption ────────────────────────────────────────────────────
    altText: {
      type: String,
      maxlength: [200, 'Alt text cannot exceed 200 characters'],
      default: '',
    },
    caption: {
      type: String,
      maxlength: [500, 'Caption cannot exceed 500 characters'],
      default: '',
    },

    // ── Status ────────────────────────────────────────────────────────────────
    isActive: {
      type: Boolean,
      default: true,
    },
  },
  { timestamps: true }
);

// Indexes
mediaSchema.index({ 'uploadedBy.userId': 1 });
mediaSchema.index({ category: 1 });
mediaSchema.index({ entityType: 1, entityId: 1 });
mediaSchema.index({ resourceType: 1 });

module.exports = mongoose.model('Media', mediaSchema);
